### ISSUE TITLE
Doesn't Work with Yosemite

### ISSUE THREAD

**Issue by joshuaneedham** [13bold/Colors#3]
The app opens but when you try and select the magnifier to lookup a color nothing happens.

**Comment by 13bold** [comment]
Unfortunately I can no longer maintain Colors, but an old partner in crime of mine, Laurent Baumann, has picked up the slack with a new Yosemite-friendly app: http://couleursapp.com

**Comment by joshuaneedham** [comment]
Sounds good. I managed to figure out how to use the digital color meter
Apples app so im good. Too bad you can't update but I'm sure youre plenty
busy at Apple.

Sincerely,
Joshua Needham
Lead Drupal Architect - WhiteClouds.com
Owner - WebMob Development, LLC
Phone - (801)452-1836
