### ISSUE TITLE
Picker not working in Yosemite)

### ISSUE THREAD

**Issue by bfred-it** [13bold/Colors#4]
The color picker is not working in Yosemite, are there any plans to support it?

![screen shot 2015-01-23 at 12 11 12](https://cloud.githubusercontent.com/assets/1402241/5873662/96a1ce0e-a2ad-11e4-9df0-08fe44a62624.png)

**Comment by 13bold** [comment]
There are not; however, Laurent picked up where Colors left off with [Couleurs](http://couleursapp.com), which *does* have full Yosemite support (and is way prettier anyway).

**Comment by bfred-it** [comment]
oooh fancy! Thanks! :)

Do you want to offer it as a 10.10 alternative in the readme? Would you accept a PR?

**Comment by 13bold** [comment]
Good idea, @bfred-it! I updated the README this evening. :+1:
