### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by vitorgalvao** [13bold/Colors#5]
Would like to include it in [homebrew-cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/colors.rb) but [these lines](https://github.com/13bold/Colors/blob/5d42fbe4f1a36c1d1681b51125e3433056d8dd9a/main.m#L5-6) are the only thing resenbling a license I find on a first look.

**Comment by mattpat** [comment]
You should consider it MIT licensed; however, do be aware that Colors is no longer actively maintained! (See the README and http://couleursapp.com)

**Comment by vitorgalvao** [comment]
> You should consider it MIT licensed

Thank you for the fast reply.

> do be aware that Colors is no longer actively maintained

I saw that in the README. The cask will be updated with that information.

Thank you again.
